language: python
sudo: false

env:
  - LUA="lua=5.1"
  - LUA="lua=5.2"
  - LUA="lua=5.3"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA # install all stuff into ./lua_install
  - export PATH=$PATH:$PWD/lua_install/bin

install:
  - luarocks install luacheck
  - luarocks install busted
  - luarocks install luacov
  - luarocks install luacov-coveralls

script:
  - luarocks make --local
  - luacheck --std max+busted *.lua
  - busted --verbose --coverage ./benchmark_spec.lua

after_success:
  - luacov-coveralls -e $TRAVIS_BUILD_DIR/lua_install
