version: 0.0.1.{build}-test

# Use default image unless needed
#os:
#- Windows Server 2012 R2

shallow_clone: true

environment:
  LUAROCKS_VER: 2.3.0
  matrix:
  - LUA_VER: 5.1.5
  - LUA_VER: 5.2.4  # Lua 5.2.4 with compatibility flags disabled.
    NOCOMPAT: true
  - LUA_VER: 5.3.2  # Lua 5.3.2 with compatibility flags disabled.
    NOCOMPAT: true

matrix:
  allow_failures:
    - configuration: 2012
    - configuration: 2015

configuration:
  - 2015
  - 2012

platform:
  - x64

cache:
  - c:\lua -> appveyor.yml
  - c:\external -> appveyor.yml


install:
# Make compiler command line tools available
- call .appveyor\set_compiler_env.bat
# Setup Lua development/build environment
- call .appveyor\install.bat

before_build:
- echo "Installing external deps"

build_script:
- luarocks make --local

before_test:
# install test only deps (if not already installed)
- luarocks show busted || luarocks install busted
- luarocks show luacov || luarocks install luacov
- luarocks show luacheck || luarocks install luacheck

test_script:
- echo "Testing..."
- luacheck --std max+busted .\benchmark.lua .\benchmark_spec.lua
- busted --verbose .\benchmark_spec.lua
